# Generated by Django 5.1.7 on 2026-09-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scenario_type', models.CharField(max_length=50)),
                ('difficulty', models.CharField(default='Intermediate', max_length=20)),
                ('sender', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('red_flags', models.JSONField(help_text='List of red flag objects with position/id, text, and explanation')),
                ('safe_explanation', models.TextField()),
                ('action_tips', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('threat_type', models.CharField(choices=[('EMAIL', 'Phishing Email'), ('SMS', 'Smishing SMS'), ('URL', 'Suspicious Web Link'), ('PAYMENT', 'Payment Request / Scam'), ('SOCIAL', 'Social Media / Impersonation')], default='EMAIL', max_length=20)),
                ('content_sample', models.TextField()),
                ('evidence_summary', models.TextField()),
                ('risk_score', models.IntegerField(default=0)),
                ('severity', models.CharField(choices=[('SAFE', 'Safe / Low Risk'), ('CAUTION', 'Caution / Suspicious'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Malicious Threat')], default='CAUTION', max_length=20)),
                ('reporter_name', models.CharField(default='Anonymous User', max_length=100)),
                ('upvotes', models.IntegerField(default=1)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
